# -*- coding: utf-8 -*-
"""trò chơi đoán số.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IhdEuj481oWbP9utrwoRhpcD5ReWKC11
"""

print("-----trò chơi đoán số-----")
import random
gioi_han_sai = 10
so_lan_sai = 0
a = random.randint(1, 100)
b = int(input("Hãy cho biết bạn chọn số nào: "))
while b != a and so_lan_sai < gioi_han_sai:
    if a < b:
        print("❌")
        print("🔽 Bé hơn 🔽")
    elif a > b:
        print("❌")
        print("🔼 Lớn hơn 🔼")
    so_lan_sai += 1
    b = int(input("Hãy cho biết bạn chọn số nào: "))
if b == a:
    print("✔️")
    print("🎉 HOAN HÔ!🎉")
    print("Số lần sai là 👍", so_lan_sai)
else:
    print("💀 Làm sai quá số lần giới hạn 10!❌")
    print("Số đúng là:", a, "✔️")

import random

gioi_han_sai = 10
so_lan_sai = 1
a = random.randint(1, 100)

while so_lan_sai <= gioi_han_sai:
    try:
        b = int(input("Hãy cho biết bạn chọn số nào: "))
        if b == a:
            print("🎉 HOAN HÔ!🎉 ")
            print("Số lần sai là 👍", so_lan_sai - 1)
            break  # Exit the loop if guessed correctly
        elif a < b:
            print("🔽 Bé hơn 🔽")
        elif a > b:
            print("🔼 Lớn hơn 🔼")
        so_lan_sai += 1
    except ValueError:
        print("⚠️ Vui lòng nhập một số hợp lệ.")

# Check if the loop finished without guessing correctly
if so_lan_sai > gioi_han_sai:
    print("💀 Làm sai quá số lần giới hạn 10!")
    print("Số đúng là", a, "👍")

import random

gioi_han_sai = 10
so_lan_sai = 1
a = random.randint(1, 100)

while so_lan_sai <= gioi_han_sai:
    try:
        b = int(input("Hãy cho biết bạn chọn số nào: "))
        if b == a:
            print("🎉 HOAN HÔ!🎉 ")
            print("Số lần sai là 👍", so_lan_sai - 1)
            break  # Exit the loop if guessed correctly
        elif a < b:
            print("🔽 Bé hơn 🔽")
        elif a > b:
            print("🔼 Lớn hơn 🔼")
        so_lan_sai += 1
    except ValueError:
        print("⚠️ Vui lòng nhập một số hợp lệ.")

# Check if the loop finished without guessing correctly
if so_lan_sai > gioi_han_sai:
    print("💀 Làm sai quá số lần giới hạn 10!")
    print("Số đúng là", a, "👍")